#======= Prison 2.0 Configuration =======#
#           (C) 2016 SirFaizdat          #
#========================================#

server-prefix: "&4Prison &7>"
check-updates: true
opt-out: false

# The enable block tells Prison whether or not to enable a component.
# Changes in this block will not take effect until the SERVER is reloaded or restarted.
enable:
  mines: true
  ranks: true
  autosmelt: true
  autoblock: true

reset-time: 10
reset-warnings: [10,5,1]
reset-warning-message: "&6Mines are going to reset in &c<mins> &6minutes."
reset-broadcast-message: "&6All mines have been reset."
fill-mode: true
async-reset: true

# Only use this if you know what you're doing!
multiworld: false
world-list: [plots, mines]