#======= Prison 2.0 Configuration =======#
#           (C) 2015 SirFaizdat          #
#========================================#

server-prefix: "&4Prison &7>"
check-updates: true

reset-time: 10
reset-warnings: [10,5,1]
fill-mode: true

# Only use this if you know what you're doing!
multiworld: false
world-list: [plots, mines]